#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define FREQ_CONTROL_HZ 50
#define FREQ_LOG_HZ 10

#define INTERVAL_CONTROL_MICROS (1000000 / FREQ_CONTROL_HZ)
#define INTERVAL_LOG_MICROS (1000000 / FREQ_LOG_HZ)

#define WHEEL_LEFT 100
#define WHEEL_LEFT_PIN_A 21
#define WHEEL_LEFT_PIN_B 17
#define WHEEL_RIGHT 200
#define WHEEL_RIGHT_PIN_A 0
#define WHEEL_RIGHT_PIN_B 0

#endif