#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define FREQ_CONTROL_HZ 200
#define FREQ_LOOP_HZ 200
#define FREQ_LOG_HZ 20
#define FREQ_LOG_META_HZ 1

#define INTERVAL_CONTROL_MICROS (1000000 / FREQ_CONTROL_HZ)
#define INTERVAL_LOOP_MICROS (1000000 / FREQ_LOOP_HZ)
#define INTERVAL_LOG_MICROS (1000000 / FREQ_LOG_HZ)
#define INTERVAL_LOG_META_MICROS (1000000 / FREQ_LOG_META_HZ)

#define WHEEL_SPEED_RESET_INTERVAL_MICROS 1000 * 400

#define WHEEL_LEFT_PIN_A 16
#define WHEEL_LEFT_PIN_B 19

#define WHEEL_RIGHT_PIN_A 21
#define WHEEL_RIGHT_PIN_B 17

#define MOTOR_PWM_FREQ 1500000 // 1.5 Mhz
#define MOTOR_PWM_RESOLUTION_BITS 16
#define MOTOR_POWER_RESOLUTION_DECIMALS 5

#define MOTOR_LEFT_IN_1 12
#define MOTOR_LEFT_IN_2 27
#define MOTOR_LEFT_PWM_PIN 33
#define MOTOR_LEFT_PWM_CHANNEL 0

#define MOTOR_RIGHT_IN_1 32
#define MOTOR_RIGHT_IN_2 15
#define MOTOR_RIGHT_PWM_PIN 13
#define MOTOR_RIGHT_PWM_CHANNEL 1

#endif